---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: '11.16.4'

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: freebsd-10.2

suites:
  - name: release
    run_list:
      - recipe[mikoi::default]
    attributes:
      mikoi:
        install_method: release
  - name: go
    run_list:
      - recipe[mikoi::default]
    attributes:
      mikoi:
        install_method: go
    excludes:
      - freebsd-10.2 # golang cookbook does not support freebsd
