---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: '12.18.31'

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: freebsd-10.2
    driver:
      synced_folders:
        - [".", "/vagrant", "type: :rsync"]

suites:
  - name: release
    run_list:
      - recipe[mikoi::default]
    attributes:
      mikoi:
        install_method: release
  - name: go
    run_list:
      - recipe[mikoi::default]
    attributes:
      mikoi:
        install_method: go
    excludes:
      - freebsd-10.2 # golang cookbook does not support freebsd
